module.exports = {
    KaercherAutoEmptyDockManualTriggerCapability: require("./KaercherAutoEmptyDockManualTriggerCapability"),
    KaercherBasicControlCapability: require("./KaercherBasicControlCapability"),
    KaercherCarpetModeControlCapability: require("./KaercherCarpetModeControlCapability"),
    KaercherCarpetSensorModeControlCapability: require("./KaercherCarpetSensorModeControlCapability"),
    KaercherCombinedVirtualRestrictionsCapability: require("./KaercherCombinedVirtualRestrictionsCapability"),
    KaercherConsumableMonitoringCapability: require("./KaercherConsumableMonitoringCapability"),
    KaercherCurrentStatisticsCapability: require("./KaercherCurrentStatisticsCapability"),
    KaercherDoNotDisturbCapability: require("./KaercherDoNotDisturbCapability"),
    KaercherFanSpeedControlCapability: require("./KaercherFanSpeedControlCapability"),
    KaercherLocateCapability: require("./KaercherLocateCapability"),
    KaercherMapSegmentEditCapability: require("./KaercherMapSegmentEditCapability"),
    KaercherMapSegmentRenameCapability: require("./KaercherMapSegmentRenameCapability"),
    KaercherMapSegmentationCapability: require("./KaercherMapSegmentationCapability"),
    KaercherObstacleAvoidanceControlCapability: require("./KaercherObstacleAvoidanceControlCapability"),
    KaercherOperationModeControlCapability: require("./KaercherOperationModeControlCapability"),
    KaercherSpeakerTestCapability: require("./KaercherSpeakerTestCapability"),
    KaercherSpeakerVolumeControlCapability: require("./KaercherSpeakerVolumeControlCapability"),
    KaercherWaterUsageControlCapability: require("./KaercherWaterUsageControlCapability"),
    KaercherWifiConfigurationCapability: require("./KaercherWifiConfigurationCapability"),
    KaercherZoneCleaningCapability: require("./KaercherZoneCleaningCapability")
};
